/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2j1yj7ikcha
 */
import { Button } from '#/components/ui/button';
import { SVGProps } from 'react';
import lifters_hq from './lifters_hq.jpg';
import Image from 'next/image';

export function HomeV0() {
  return (
    <div className="flex h-screen flex-col">
      <main className="flex-1 overflow-y-auto">
        <div className="grid gap-4 p-4 md:gap-8 lg:p-8">
          <div className="flex items-center space-x-4">
            <Image
              alt="Avatar"
              className="rounded-full border"
              height="64"
              src={lifters_hq}
              style={{
                aspectRatio: '64/64',
                objectFit: 'cover',
              }}
              width="64"
            />
            <div className="space-y-1">
              <h1 className="text-2xl font-bold">Lifters HQ</h1>
              <div className="flex items-center space-x-2 text-sm">
                <div className="flex items-center space-x-1">
                  <TrophyIcon className="h-4 w-4 text-gray-500" />
                  <span className="font-semibold">1st</span>
                </div>
                <div className="flex items-center space-x-1">
                  <UserIcon className="h-4 w-4 text-gray-500" />
                  <span className="font-semibold">John</span>
                </div>
                <div className="flex items-center space-x-1">
                  <UserIcon className="h-4 w-4 text-gray-500" />
                  <span className="font-semibold">Doe</span>
                </div>
              </div>
            </div>
          </div>
          <div className="grid gap-4">
            <div className="flex items-center justify-between rounded-xl border p-4">
              <div className="space-y-1">
                <h2 className="text-lg font-semibold">Join the Challenge</h2>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Join the challenge to get fit in 30 days.
                </p>
              </div>
              <Button size="sm">Join</Button>
            </div>
          </div>
          <div className="grid gap-4">
            <div className="flex items-center justify-between rounded-xl border p-4">
              <div className="space-y-1">
                <h2 className="text-lg font-semibold">Day 1: Run 1 mile</h2>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  {/* eslint-disable-next-line react/no-unescaped-entities */}
                  You haven't started this task yet.
                </p>
              </div>
              <Button size="sm">Start</Button>
            </div>
            <div className="flex items-center justify-between rounded-xl border p-4">
              <div className="space-y-1">
                <h2 className="text-lg font-semibold">Day 2: Walk 2 miles</h2>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  {/* eslint-disable-next-line react/no-unescaped-entities */}
                  You haven't started this task yet.
                </p>
              </div>
              <Button size="sm">Start</Button>
            </div>
            <div className="flex items-center justify-between rounded-xl border p-4">
              <div className="space-y-1">
                <h2 className="text-lg font-semibold">Day 3: Cycle 5 miles</h2>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  {/* eslint-disable-next-line react/no-unescaped-entities */}
                  You haven't started this task yet.
                </p>
              </div>
              <Button size="sm">Start</Button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

function FlagIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  );
}

function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function TrophyIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>
  );
}

function UserIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
